### ISSUE TITLE
السلام عليكم / فيه مشاكل كتير 

### ISSUE THREAD

**Issue by azabcodes** [alheekmahlib/alquranalkareem#1]

**Comment by alheekmahlib** [comment]
وعليكم السلام ورحمة الله وبركاته، لو ممكن تحدد لي اين هي المشاكل لكي أقوم بأصلاحها، بارك الله فيكSent from my iPhoneOn Feb 3, 2023, at 8:23 AM, Mahmoud Azab ***@***.***> wrote:﻿

**Comment by alheekmahlib** [comment]
أخي الحبيب، أتمنى منك ذكر الأخطاء الكثيرة التي تقول عنها
