### ISSUE TITLE
دعم أمكانية الوصول Accessibility support

### ISSUE THREAD

**Issue by MesterPerfect** [alheekmahlib/alquranalkareem#27]
السَلام عليكم ورحمة الله وبركاته 
بارك الله مجهوداتكم وجعلها الله في ميزان حسناتكم
هل يمكنكم تطبيق إرشادات Flutter المتعلقة بإمكانية الوصول 
سواء في التطبيق أو في الموقع 
لكي يستطيع مستخدمي قارئات الشاشة الإستفادة من المحتوى المقدم 
وجزاكم الله خيرا 

https://docs.flutter.dev/ui/accessibility-and-localization/accessibility

**Comment by alheekmahlib** [comment]
وعليكم السلام ورحمة الله وبركاته

بارك الله فيك أخي الكريم، بإذن الله في التحديثات القادمة سنحاول إضافة إمكانية الوصول في التطبيق.

**Comment by MesterPerfect** [comment]
وفيكم الله بارك 
في الإنتظار إن شاء الله

**Comment by alheekmahlib** [comment]
هل إمكانية الوصول تدعم أي لغة ام فقط الانجليزية؟

**Comment by MesterPerfect** [comment]
> هل إمكانية الوصول تدعم أي لغة ام فقط الانجليزية؟

بالطبع كل اللغات 
هي ليست متعلقة باللغة 
بل هي تحسينات على الكود

**Comment by MesterPerfect** [comment]
على سبيل المثال 
هناك كثير من الأزرار عبارة عن أيقونات فقط 
ولا يوجد اسم للزر 
وهذا زر لا يتوافق مع امكانية الوصول

**Comment by alheekmahlib** [comment]
نعم انا فاهمك الآن انا عملتها لكن احاول اخليها تدعم اللغة العربية بإذن الله

**Comment by MesterPerfect** [comment]
> نعم انا فاهمك الآن انا عملتها لكن احاول اخليها تدعم اللغة العربية بإذن الله

لا تقلق، طالما التسميات انضافت للأزرار 
فستعمل مع كل اللغات
