### ISSUE TITLE
مشكلة في الخط تداخل الحركات

### ISSUE THREAD

**Issue by elBAKRIN** [alheekmahlib/alquranalkareem#37]
مشكلة بالخط بعد تحديثات flutter
المشكلة الموجودة بالتطبيق تداخل الحركات في بعض الآيات
لدي نفس المشكلة بتطبيقي وكنت ابحث عن حل لها ووجدتها موجودة بتطبيقكم

**صورة للمشكلة** 
![1704101533036](https://github.com/alheekmahlib/alquranalkareem/assets/69627568/f7cbbf27-52a6-42ce-a8ca-3ee5596fae7f)

![1704101533055](https://github.com/alheekmahlib/alquranalkareem/assets/69627568/ddd61e5a-4871-4302-af54-d94ef82c8905)

طبعن موجودة بعدة صفحات وطرق مختلفة للتداخل
علمن ان المشكلة غير موجودة في اصدارات flutter القديمة
في حال توصلتم الى حل اتمنى الرد بطريقة الحل وسبب المشكلة

**تحديث**
تقريبا المشكلة من Material3
بعد ايقافها اختفت المشكلة مصادفة
useMaterial3: false,

**Comment by elBAKRIN** [comment]
تقريبا المشكلة من Material3 
بعد ايقافها اختفت المشكلة مصادفة 
useMaterial3: false,

**Comment by alheekmahlib** [comment]
وعليكم السلام ورحمة الله وبركاته، حياك الله وبياك أخي الكريم، سبحان الله يوم أمس كنت أحاول أن أجد حل للمشكلة، بارك الله فيك أخي الكريم
