### ISSUE TITLE
[Bug] 🐞 The surah does not appear when certain conditions are met

### ISSUE THREAD

**Issue by moha-b** [alheekmahlib/alquranalkareem#43]
https://github.com/alheekmahlib/alquranalkareem/assets/73842931/9bca2db7-8418-46b4-9fc4-df2225d812a0

## Steps to reproduce the error
1 - Open the Qur’an and choose any image that will work normally
2 - Return to the home page
3 - Read the Qur’an again
4 - From the side menu on the Quran page, choose any image
5 - repeat steps 2 and 3.

## Environment 
I try it only on my phone **Samsung Galaxy A21s** android version `12`

### كل عام وانت بخير رمضان كريم 🎈 🥳

**Comment by alheekmahlib** [comment]
Salam brother, I tried the app and everything works. 
I think the code you are using is an old code. 
Try pulling the new code.

رمضان مبارك وكل عام وأنت أقرب إلى الله

**Comment by moha-b** [comment]
وعليكم السلام 
والله انا مش عارف ايه الى بيحصل الصراحة 😅  هو فعلا كان فى update انا حملت ال update  بس نفس المشكلة لسا موجودة 

https://github.com/alheekmahlib/alquranalkareem/assets/73842931/a970ef2e-4318-4ef3-a8b3-cd17cf679251

و علشان اتاكد جربتها من هاتف والدى وهو شغال سليم فالمشكلة من عندى انا بس تقريبا 😅 فام مسحتوا وحملتوا من جديد واشتغل مظبوط الحمد لله بس فى حاجات كتير بسيطة لاحظتها 

هذه مظبوطة فى كل ال themes الا الداكنة 

![WhatsApp Image 2024-04-02 at 09 29 10_67631958](https://github.com/alheekmahlib/alquranalkareem/assets/73842931/2caa0b5c-2928-4f90-a900-d4ef71f23413)

هذه من هاتف والدى  (Oppo)

![WhatsApp Image 2024-04-02 at 09 29 42_8ea01bb4](https://github.com/alheekmahlib/alquranalkareem/assets/73842931/8e28bcc5-f4d9-4984-afdc-af5789a401a7)

**Comment by alheekmahlib** [comment]
ما شاء الله بارك الله فيك، المشكلة الأولى الخاصة باللون تم حلها الحمد لله، وبإذن الله أحل المشكلة القانية.

بارك الله فيك على التنبيه وجزاك الله خيرًا

**Comment by moha-b** [comment]
بارك الله فينا وفيك اخى جزاك الله كل خير على هذا المجهود

**Comment by moha-b** [comment]
السلام عليكم @alheekmahlib كنت اريد ان اضيف خاصية مواقيت الصلاة فى البداية كنت اريد ان create issue بها اولا بعد ذلك نقوم بال PR بغلقها لكن فى البداية اريد ان اقوم بانشاء template لل issues سواء bug or feature request انها ليست ضرورية لاكنها افضل للتنظيم كنت اريد ان اطلب منك ان تسمح لى بانشاء هذه الاشياء من فضلك 🙏

**Comment by alheekmahlib** [comment]
وعليكم السلام ورحمة الله وبركاته، لو ممكن تراسلني على الواتس حتى نتفاهم +19712278630
